# Site
name: 'UCL AI Centre Posts'
description: 'UCL AI Centre'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''

disqus: 'uclaicentre'
email: 'aicentre@cs.ucl.ac.uk'

include: ["_pages"]
permalink: /:title/

future: true

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors: 
    davidbarber:
      name:           davidbarber
      site:           http://web4.cs.ucl.ac.uk/staff/D.Barber/pmwiki/pmwiki.php
      avatar:         /assets/images/avatar1.jpg
      bio:            "David is the Director of the UCL Centre for Artificial Intelligence"
      email:          david.barber@ucl.ac.uk
      twitter:        https://twitter.com/davidobarber

    admin:
      name:           admin
      site:           
      avatar:         /assets/images/avatar2.jpg
      bio:            "UCL admin team"
      email:          aicentre@cs.ucl.ac.uk
      twitter:        https://twitter.com/uclaicentre

    harshil:
      name:           harshil
      site:           
      avatar:         /assets/images/avatar1.jpg
      bio:            "Harshil Shah is a PhD student at the UCL AI Centre"
      email:          
      twitter:        

 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]